// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transenvios.Shipping.Api.Infraestructure;

#nullable disable

namespace Transenvios.Shipping.Api.Migrations.MySqlMigrations
{
    [DbContext(typeof(MySqlDataContext))]
    [Migration("20230102053338_CP20-add-people-to-shipment")]
    partial class CP20addpeopletoshipment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Transenvios.Shipping.Api.Domains.CatalogService.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Transenvios.Shipping.Api.Domains.CatalogService.ShipmentRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<decimal?>("AdditionalKiloPrice")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("FromCityCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<decimal?>("InitialKiloPrice")
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("PriceCm3")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("ToCityCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("FromCityCode", "ToCityCode")
                        .IsUnique();

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("Transenvios.Shipping.Api.Domains.ClientService.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<sbyte?>("CountryCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("DocumentId")
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Role")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Transenvios.Shipping.Api.Domains.DriverService.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<sbyte?>("CountryCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("DocumentId")
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PickUpAddress")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("PickUpCityId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("Transenvios.Shipping.Api.Domains.ShipmentOrderService.ShipmentOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DropOffAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DropOffCityId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal?>("InitialPrice")
                        .HasColumnType("decimal(20,2)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ModifyUserId")
                        .HasColumnType("char(36)");

                    b.Property<sbyte>("PaymentState")
                        .HasColumnType("tinyint");

                    b.Property<string>("PickUpAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PickUpCityId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<sbyte?>("RecipientCountryCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("RecipientDocumentId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RecipientDocumentType")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("RecipientEmail")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RecipientFirstName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RecipientLastName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RecipientPhone")
                        .HasColumnType("varchar(10)");

                    b.Property<sbyte?>("SenderCountryCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("SenderDocumentId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SenderDocumentType")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SenderFirstName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SenderLastName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SenderPhone")
                        .HasColumnType("varchar(10)");

                    b.Property<sbyte>("ShipmentState")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(20,2)");

                    b.Property<Guid?>("TransporterId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ShipmentOrders", (string)null);
                });

            modelBuilder.Entity("Transenvios.Shipping.Api.Domains.ShipmentOrderService.ShipmentOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("Height")
                        .IsRequired()
                        .HasColumnType("decimal(20,2)");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<decimal?>("InsuredAmount")
                        .HasColumnType("decimal(20,2)");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Length")
                        .IsRequired()
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("Weight")
                        .IsRequired()
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("Width")
                        .IsRequired()
                        .HasColumnType("decimal(20,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ShipmentOrderItems", (string)null);
                });

            modelBuilder.Entity("Transenvios.Shipping.Api.Domains.UserService.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(5)");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Role")
                        .HasColumnType("char(2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
